os: linux
language: ruby
cache: bundler
rvm: 2.6.3

jobs:
  include:
    - stage: "Verify"
      name: "Run Jekyll Build"
      before_script: chmod +x ./cibuild.sh
      script: ./cibuild.sh

    - stage: "Create draft release"
      script: true
      if: tag IS present
      name: "Deploy"
      before_deploy:
        - jekyll clean
        - export CLEAN_VERSION=${TRAVIS_TAG//v/}
        - sed -i.bak "s/version:\sDev/version:\s$CLEAN_VERSION/" _config.yml
        - rm *.bak
        - export ZIP_FILENAME="system-specs-${TRAVIS_TAG}"
        - mkdir $ZIP_FILENAME
        - cp README.md LICENSE _config.yml $ZIP_FILENAME
        - mv _site ${ZIP_FILENAME}/
        - zip -qr ${ZIP_FILENAME}.zip $ZIP_FILENAME
      deploy:
        provider: releases
        token:
          secure: "Bj7QNCliAuQ6Rizjr4WyW+Iu4zovUbGZD0Cv5v4tQYlCYi/GYWcUId7D4wTiKVDFChCf3K/JMffUhV4mcYf4OmucWye/kABso+baeQ1kDsLePmekXdvHHPJCMVsIucH3Q6M10/P5jx/f0/Zi2wbclWICCnMfe0Z0fcSrzb8nObjzYXYGiAoxXUnyrMVPqgdzI5qy10t3PnB0JgHnfffV5yICxgqHt5sXCXzUBd9ceXVkU/EKeBYX5m2WnPFF4O1v6FugSp5gcs9TLZgoZfwLfFaLzaOs944dBUoSeAx9rY3cpK0MH/cl31W8aZvOZ9JPaPYIkcObgd/uz+OVitiVC37njqcMxKAZAvSL14dtC3oGPTO8qLGaNh7qFvqhlk7h11dUKYMBEhdbv8dZtUoZC4Nk3Ad9B+f1/EqhoLBGvCqNukmejZK+wH1Jty7DgUFWvc2KkKTxMStGaMZN04MnFcIFHrHijXCq+WT6xB0SJugZajkLQiF/FF89bY9sCB6QD0Ux7XJ544fcbKwJRYcj7vmXAXgwfj65X4l37PTBMt50Ig97e3AgFYZUNY7V6LP9Qnc3lwfOVZvxEu68L+W1BfcgT/PYZ3WgPDrEEBYA4gwjpzwnkLo1MJQslvHvBVGgF2w+NKggQlArBAaHvdiYyQqFNAgD5BGaaJOxBeNx7rs="
        file: "${ZIP_FILENAME}.zip"
        name: "$TRAVIS_TAG"
        skip_cleanup: true
        draft: true
        overwrite: true
        on:
          tags: true
