name: build
on: [push, create]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6.3'
          bundler-cache: true
      - run: bundler exec htmlproofer ./_site --external_only
  verify-build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6.3'
          bundler-cache: true
      - run: bundler exec jekyll build
  create-artifact:
    runs-on: ubuntu-latest
    needs: [lint, verify-build]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6.3'
          bundler-cache: true
      - run: |
          bundle exec jekyll clean
          "sed -i.bak \"s/version: Dev/version: $CLEAN_VERSION/\" _config.yml"
          rm *.bak
          mkdir dist
          cp README.md LICENSE _config.yml dist/
          mv _site dist/
          zip -qr dist.zip dist
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            dist.zip
  draft-release:
    runs-on: ubuntu-latest
    needs: create-artifact
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
      - run: |
          TAG=${GITHUB_REF//refs\/tags\//}
          ZIP_FILENAME="system-specs-${TAG}.zip"
          mv dist.zip $ZIP_FILENAME
          echo "{ZIP_FILENAME=$ZIP_FILENAME}" >> $GITHUB_ENV
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: "${{ZIP_FILENAME}}"
